
<h2>Notes</h2>
<p>This release of the Python agent adds the <a href="/docs/agents/python-agent/attributes/python-agent-attributes">request.uri attribute</a> on transaction events in insights, adds built-in cheroot instrumentation, adds support for recording flask-restful/flask-restplus exceptions, and contains bug fixes.</p>
<p>The agent can be installed using easy_install/pip/distribute via the <a href="https://pypi.python.org/pypi/newrelic">Python Package Index</a> or can be downloaded directly from the New Relic <a href="http://download.newrelic.com/python_agent/release">download site</a>.</p>
<h2>Improved Features</h2>
<ul>
  <li>
    <p><strong>Add request.uri attribute to transaction and error events</strong></p>
    <p>The Python agent will now report request.uri as an attribute on transaction events and error events. To disable this feature, add request.uri to the attributes.exclude list in the newrelic.ini configuration file.</p>
  </li>
  <li>
    <p><strong>Record Flask RESTful and Flask RestPlus exceptions</strong></p>
    <p>Since <a href="https://pypi.python.org/pypi/Flask-RESTful">Flask RESTful</a> and <a href="https://pypi.python.org/pypi/flask-restplus">Flask RestPlus</a> handle all errors that are raised in their handlers, these errors were not being captured by the normal Flask instrumentation in the Python agent. Exception handling has now been added for these two components.</p>
  </li>
  <li>
    <p><strong>Add instrumentation hooks for the Cheroot WSGI server</strong></p>
    <p>Any customers using <a href="https://pypi.python.org/pypi/Cheroot/6.0.0">Cheroot</a> with an unsupported application framework will now see data reported in New Relic APM.</p>
  </li>
</ul>
<h2>Bug Fixes</h2>
<ul>
  <li>
    <p><strong>Fix CherryPy ignore by status code for exceptions using reason phrases</strong></p>
    <p>CherryPy accepts string values for HTTPError status (reason phrases). When creating HTTPError exceptions in this way, responses were not properly ignored by status code. Responses generated by HTTPError exceptions using reason phrases are now properly ignored.</p>
  </li>
  <li>
    <p><strong>Using send_file with Flask Compress middleware may have caused an application crash</strong></p>
    <p>When using browser monitoring auto instrumentation on an application using Flask Compress, the use of the Flask send_file helper to send html files resulted in an application crash. This issue has now been resolved.</p>
  </li>
  <li>
    <p><strong>Fix incorrect parenting for traces of coroutines scheduled with asyncio gather/ensure_future</strong></p>
    <p>Coroutines scheduled with asyncio gather/ensure_future may have been reported as being a child of the wrong function. This issue has now been corrected.</p>
  </li>
</ul>
